name: Qualys Manual Scan 
on: workflow_dispatch
jobs:
    Qualys_iac_scan:
        runs-on: ubuntu-latest
        name: Qualys IaC Scan
        steps:
          - name: Checkout
            uses: actions/checkout@v2 
            with:
                fetch-depth: 0
    
          - name: Qualys IAC scan action step
            uses: QIntegration/github_action_qiac@main
            id: qiac
            env:
                URL: 'https://qualysguard.qg1.apps.qualys.ca'
                UNAME: 'quays9ns9'
                PASS: 'Niksin@98015'
            with:
              directory: '/'
